---
- name: Ensure namespace exists
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
  ignore_errors: yes

- name: Create permissions
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', 'foo-permissions.yml.j2') | from_yaml }}"

- name: Create CRD
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', 'foo-crd.yml.j2') | from_yaml }}"

- name: Deploy foo controller
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', 'deployment.yml.j2') | from_yaml }}"

- name: Deploy foo pods deployment
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', 'foo-deploycustom.yml.j2') | from_yaml }}"
