---
- name: Check running VM status (KubeVirt only)
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    api_version: kubevirt.io/v1
    kind: VirtualMachineInstance
    namespace: "{{ namespace }}"
  register: vmi
  until: vmi.resources | length > 0
  retries: 30
  ignore_errors: yes
