---
- name: Create namespace
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
    state: present

- name: Deploy DataVolume
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    definition: "{{ lookup('template', 'data-volume.yaml.j2') | from_yaml }}"
