---
- name: Check config map
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: ConfigMap
    namespace: "{{ namespace }}"
    name: "{{ confmap_name }}"
  register: config_map
  until: (config_map.resources | length > 0) and (config_map.resources[0].data.get("redis-config", "") != "")
  retries: 30
  delay: 5

- name: Check redis app
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - app={{ app_name }}
    field_selectors:
      - status.phase=Running
  register: redis
  until: >-
    redis.resources|default([])|length > 0 and
    redis | json_query('resources[*].status.containerStatuses[*].ready') | flatten |difference( [true] ) | length  == 0
  retries: 30
  delay: 5

- name: Get pod name
  set_fact:
    pod_name: "{{ redis.resources[0].metadata.name }}"

- name: Verify max memory configuration
  shell: "kubectl exec {{ pod_name }} -n {{ namespace }} -c {{ app_name }} -- redis-cli CONFIG GET maxmemory"
  register: memory_command
  until: (memory_command.stdout is search("maxmemory")) and (memory_command.stdout is search("2097152"))
  retries: 5
  delay: 5

- name: Verify memory policy configuration
  shell: "kubectl exec {{ pod_name }} -n {{ namespace }} -c {{ app_name }} -- redis-cli CONFIG GET maxmemory-policy"
  register: memory_command
  until: (memory_command.stdout is search("maxmemory-policy")) and (memory_command.stdout is search("allkeys-lru"))
  retries: 5
  delay: 5
