---
- name: Clean up application
  import_tasks: cleanup.yml
  when: with_cleanup | default(false) | bool

- name: Deploy application
  import_tasks: deploy.yml
  when: with_deploy | default(false) | bool

- name: Validate application
  import_tasks: validate.yml
  when: with_validate_source | default(false) | bool or with_validate_target | default(false) | bool
