---
- name: Check datagrid pods status
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - application=datagrid-service
  register: pods
  until: >-
    pods.resources|default([])|length > 0 and
    pods | json_query('resources[*].status.containerStatuses[*].ready') | flatten |difference( [true] ) | length  == 0
  retries: 60
  delay: 15
  ignore_errors: yes
