---
- name: Sleep for a while to wait pod start
  pause:
    seconds: 60

- name: Check pod number
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - app={{ app_name }}
    field_selectors:
      - status.phase=Running
  register: pod

- name: Check pod count before stage migration
  fail:
    msg: "There should be one pod present before stage migration."
  when: with_before_stage_migration | default(false) | bool == true and pod.resources | length != 1

- name: Check pod count after stage migration
  fail:
    msg: "There should be no pod present after stage migration."
  when: with_before_stage_migration | default(false) | bool == false and pod.resources | length != 0

- name: Check PVCs status
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: PersistentVolumeClaim
    namespace: "{{ namespace }}"
    label_selectors:
      - app={{ app_name }}
  register: app_pvc

- fail:
    msg: "There should be two PVC present after the stage migration."
  when: app_pvc.resources | length != 2

- fail:
    msg: "PVC {{ item.metadata.name }} should be bound, before and after the migration."
  when: item.status.phase != 'Bound'
  loop: "{{ app_pvc.resources }}"
  loop_control:
    label: "check if PVC {{ item.metadata.name }} is bound in namespace {{ item.metadata.namespace }}"

- name: Validate the volume
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    definition: "{{ lookup('template', 'validate_pod_two_pvs_base_data.yml.j2') | from_yaml }}"

- name: Wait until validation is done
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - app={{ app_name }}-validate-base
    field_selectors:
      - status.phase=Succeeded
  register: pod
  until: pod.resources | length > 0
  retries: 30
