---
- name: Ensure namespace exists
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Ensure namespace is present
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Namespace
    name: "{{ namespace }}"
  register: ns_check
  until: ns_check.resources | length > 0
  retries: 6
  delay: 5

- name: Deploy application
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    definition: "{{ lookup('template', 'deployment.yml.j2') | from_yaml_all | list }}"

- name: Check database pod status
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - app={{ db_name }}
    field_selectors:
      - status.phase=Running
  register: db_pod
  until: >-
    db_pod.resources|default([])|length > 0 and
    db_pod | json_query('resources[*].status.containerStatuses[*].ready') | flatten |difference( [true] ) | length  == 0
  retries: 30
  delay: 3

- name: Check application pod status
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - app={{ app_name }}
    field_selectors:
      - status.phase=Running
  register: app_pod
  until: >-
    app_pod.resources|default([])|length > 0 and
    app_pod | json_query('resources[*].status.containerStatuses[*].ready') | flatten |difference( [true] ) | length  == 0
  retries: 30
  delay: 3

- name: Wait until service is ready for connections
  ansible.builtin.command: >
    kubectl logs {{ (db_pod.resources|first).metadata.name }}
    -n {{ namespace }}
  register: result
  until: result.stdout is search('socket.*/var/lib/mysql/mysql.sock.*port.*3306')
  retries: 30
  changed_when: false

- name: Wait until API server starts
  ansible.builtin.command: >
    kubectl logs {{ (app_pod.resources|first).metadata.name }}
    -n {{ namespace }}
  register: result
  until: result.stdout is search('Starting Todolist API server')
  retries: 30
  changed_when: false

- name: Add additional items to todo list
  ansible.builtin.command: >
    kubectl exec {{ (db_pod.resources|first).metadata.name }}
    -n {{ namespace }}
    -- mysql -u root todolist -e 'insert into todo_item_models values(6, "Test string", 0)'
  changed_when: false

- name: Wait for 30 seconds
  pause:
    seconds: 30
