---
- name: Check pods status
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - app={{ app_name }}
  register: pod
  until: >-
    pod.resources|default([])|length > 0 and
    pod | json_query('resources[*].status.containerStatuses[*].ready') | flatten |difference( [true] ) | length  == 0
  retries: 100
  delay: 3

- name: Obtain route (OpenShift only)
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Route
    namespace: "{{ namespace }}"
    label_selectors:
      - app=nginx
  register: nginx_route
  ignore_errors: yes

- set_fact:
    expected_num_visits: "{{ num_visits if expected_num_visits is not defined else expected_num_visits }}"
    cacheable: yes

- name: Access the html file
  uri:
    url: http://{{ nginx_route.resources[0].spec.host }}
    method: GET
    status_code: 200
  register: res
  retries: 30
  delay: 10
  until: res is success
  when: nginx_route.resources | length > 0

- name: Get /var/log/nginx/access.log file content
  ansible.builtin.command: >
    kubectl exec $(kubectl get pods -n {{ namespace }} -l app={{ app_name }} -o jsonpath='{.items[0].metadata.name}') -n {{ namespace }} -- cat /var/log/nginx/access.log
  register: output
  until: output.rc == 0 and output.stdout != ''
  retries: 5
  changed_when: false

- debug:
    msg: "{{ output.stdout_lines }}"
    var: output.stdout_lines

- name: Fail if no 403 error present in nginx access.log file
  fail:
    msg: "There must be 1 error in nginx access.log file but got {{ output.stdout_lines | select('search', '403') | list | length }}"
  when: output.stdout_lines | select('search', '403') | list | length != 1
