---
int_app_name: internal-cronjob
ext_app_name: external-cronjob

internal_image_name: internal-alpine
internal_image_tag: int
external_image_name: quay.io/openshifttest/alpine:latest

with_cleanup: false
with_deploy: false
with_validate: false

with_deploy_internal_external_images: false
with_deploy_with_pvc: false

with_validate_internal_external_images: false
with_validate_with_pvc: false
