---
- name: Delete external job
  k8s:
    state: absent
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ ext_app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete internal job
  k8s:
    state: absent
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ int_app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
  when: is_openshift | default(false)
