---
- name: Check quota setting
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: ResourceQuota
    namespace: "{{ namespace }}"
  register: quota
  retries: 20
  until: quota.resources | length > 0
