---
- name: Ensure namespace exists
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Deploy daemonset
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', 'deployment-daemonset.yml.j2') | from_yaml }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
  vars:
    app_name: "{{ daemonset.app_name }}"

- name: Deploy replicaset
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', 'deployment-replicaset.yml.j2') | from_yaml }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
  vars:
    app_name: "{{ replicaset.app_name }}"
    replicas: "{{ replicaset.replicas }}"

- name: Deploy statefulset
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', 'deployment-statefulset.yml.j2') | from_yaml }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
  vars:
    app_name: "{{ statefulset.app_name }}"
    replicas: "{{ statefulset.replicas }}"
