---
- name: Delete cronjob
  k8s:
    state: absent
    definition:
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: "{{ ext_app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
