---
replicas: 1
int_app_name: internal-nginx
ext_app_name: external-nginx
external_image_name: quay.io/openshifttest/alpine:latest
internal_image_name: internal-alpine
internal_image_tag: int

with_cleanup: false
with_deploy: false
with_validate_source: false
with_validate_target: false

