---
app_name: 'foo-crdcontroller'
foo_name: 'example-deployment'

with_deploy: false
with_cleanup: false
with_validate: false


apis:
  crd:
    default: "apiextensions.k8s.io/v1"
  deployment:
    default: "apps/v1"
  clusterrolebinding:
    default: "rbac.authorization.k8s.io/v1"

deployment_api: "{{ apis.deployment.get(cluster_version, apis.deployment.get('default')) }}"
clusterrolebinding_api: "{{ apis.clusterrolebinding.get(cluster_version, apis.clusterrolebinding.get('default')) }}"
crd_api: "{{ apis.crd.get(cluster_version, apis.crd.get('default')) }}"
