---
- name: Ensure namespace exists
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Deploy robot shop sample application
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    definition: "{{ lookup('template', 'manifest.yml') | from_yaml_all | list }}"

- name: Wait for mysql pod to start running
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - service=mysql
    field_selectors:
      - status.phase=Running
  register: mysql_pod
  until: "true in (mysql_pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 30

- name: Wait until mysql database initialization is done
  ansible.builtin.command: >
    kubectl logs {{ (mysql_pod.resources|first).metadata.name }}
    -n {{ namespace }}
  register: result
  until: result.stdout is search('socket:.*sock.*port:.*3306  MySQL Community Server \\(GPL\\)')
  retries: 15
  delay: 40
  changed_when: false
