---
- name: Check robot-shop application resources status
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - service={{ item }}
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 60
  delay: 15
  loop:
    - "cart"
    - "catalogue"
    - "dispatch"
    - "mongodb"
    - "mysql"
    - "payment"
    - "rabbitmq"
    - "ratings"
    - "redis"
    - "shipping"
    - "user"
    - "web"

- name: Obtain robot-shop application route (OpenShift only)
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Route
    namespace: "{{ namespace }}"
    name: "front-end"
  register: robot_shop_route
  ignore_errors: yes

- debug:
    msg: "Will check robot-shop application at http://{{ robot_shop_route.resources[0].spec.host }}"
  when: robot_shop_route.resources | length > 0

- name: Verify that robot-shop application is available
  uri:
    url: "http://{{ robot_shop_route.resources[0].spec.host }}"
    method: GET
    return_content: yes
  register: uri
  until: "'Robot' in uri.content"
  retries: 6
  delay: 10
  when: robot_shop_route.resources | length > 0
