---
- name: Create storage class
  k8s:
    state: present
    definition: "{{ lookup('template', 'storageclass.yml.j2') | from_yaml }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
