---
- name: Delete MySQL deployment
  k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete MySQL service
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete MySQL secret
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete MySQL PVCs
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
  loop:
    - "{{ app_name }}-data"
    - "{{ app_name }}-data1"
